### ISSUE TITLE
Multi-viewport window glitching

### ISSUE THREAD

**Issue by ihm-tswow** [VesCodes/ImGui#19]
ImGui windows created in the main viewport seem to glitch out badly when moved to the edges of the screen when running a game in standalone.

- In fullscreen, it causes the imgui window to shrink down like in the image below (this seems to have started with the very latest commit, but it still pops really badly in the previous releases as well). This also seems to happen if the game window is resized.
![image](https://github.com/user-attachments/assets/9468a87e-0dcd-4e8a-9436-ef53078c9833)

- In windowed mode, IMGui windows can leave the main window, but are stuck on the same monitor as the game itself (they can extend further, but cannot be dragged off to the separate monitor entirely). This seems to be the case on both the latest and previous commits.

- Disabling viewports using `ImGui::GetIO().ConfigFlags &= ~ImGuiConfigFlags_ViewportsEnable;` stops the imgui windows from trying to pop out of the game window, but instead causes incorrect mouse input location whenever the game window is located anywhere but the top-left corner of the monitor.

- Using `ImGui::SetNextWindowViewport(ImGui::GetMainViewport()->ID);` before individual windows seems to work for now with correct mouse input location. The demo window will occasionally break with this approach, probably as the main demo window isn't always drawn first when you call that function.

Commit: https://github.com/VesCodes/ImGui/commit/67b82c1812b70e9a53f7f2142a49c8cee6d33c2c
Unreal: 5.4.3
Platform: Windows 10

**Comment by VesCodes** [comment]
(1a) The shrinking issue should be fixed in https://github.com/VesCodes/ImGui/commit/097e82f6de866a25f8029e714722572b57a878da
(1b) Curious to get some more info on the bad popping you mention - would you be able to provide a video? While trying to repro this I did notice that in exclusive fullscreen mode there is a black flash when an ImGui window is dragged outside the game viewport and consequently transferred to a separate native window. This doesn't happen in borderless fullscreen mode.
(2) I can't seem to reproduce this, can you confirm you're still seeing this on latest?

**Comment by VesCodes** [comment]
(3) Mouse position issue should be fixed in https://github.com/VesCodes/ImGui/commit/1eb5e613e8a3bfbe020cf1496858d38ee6fee078

I'll leave this open for now so we can follow up on the popping issue :)
